parameters:
#    ed_front_end.example.class: ED\FrontEndBundle\Example

services:
#    ed_front_end.example:
#        class: %ed_front_end.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
